apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-deployment
  labels:
    app: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
      - name: my-application-container
        image: your-docker-image-path:tag # Replace with your Docker image path and tag
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  type: NodePort
  selector:
    app: my-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-application-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-application-deployment
  minReplicas: 2 # Minimum number of pods
  maxReplicas: 5 # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Target average CPU utilization percentage
